### ISSUE TITLE
Build pycharm without creating the developer user

### ISSUE THREAD

**Issue by Amschel** [rycus86/docker-pycharm#1]
Hi,

I tried to build your version of dockerfile but since it creates an user, when I run pycharm it doesn't see the correct system env. Is it possible to build everything in root?

Thank you!

**Comment by rycus86** [comment]
Hi,

Thanks for trying the image!
I wanted to avoid running it with the root user for security reasons.
The developer user should be able to use `pip` to install any packages you need, is this what you meant by system env?
If you need environment variables, just pass them to the container with `-e KEY=VALUE` on the `docker run` command.

If you absolutely need `root`, you're welcome to fork the repo, remove the user generation lines in the Dockerfile and build it.
I'm happy to help with it if you need it.

Thanks!

**Comment by Amschel** [comment]
Well, the problem is that I have a dockerfile that creates an image with nvidia drivers, cuda, cudnn and some deep learning framework. What I did was to append your dockerfile content to that dockerfile but python is unable to locate the path of cuda. If I just start the container without starting pycharm,  and I try to run something that uses cuda, it's able to find the path.

**Comment by rycus86** [comment]
I see. I think you could try setting the environment variables after the `USER` instruction in the Dockerfile. I never tried cuda, but the docs say:

```shell
$ export PATH=/usr/local/cuda-9.1/bin${PATH:+:${PATH}}
$ export LD_LIBRARY_PATH=/usr/local/cuda-9.1/lib64\
                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

Can you try this?

**Comment by Amschel** [comment]
Hi,

I tried but it doens't find the path:
"""
Step 15/18 : RUN export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}} &&   export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
 ---> Running in 3ca38093d9cb
/bin/sh: 1: export: :/usr/local/nvidia/lib:/usr/local/nvidia/lib64: bad variable name
The command '/bin/sh -c export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}} &&   export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}' returned a non-zero code: 2
"""

**Comment by Amschel** [comment]
Thank you! It worked.

**Comment by Amschel** [comment]
I noticed something about running pycharm in root.

```
[root@localhost Downloads]# nvidia-docker run -it -v /tmp/.X11-unix/:/tmp/.X11-unix/ -v ~/PycharmProjects:/root/PycharmProjects -v ~/.PyCharm:/root/.PyCharm -e DISPLAY=$DISPLAY --rm tensorflow /etc/pycharm/bin/pycharm.sh
No protocol specified

Start Failed: Failed to initialize graphics environment

java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:128)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1734)
	at java.awt.EventQueue.isDispatchThread(EventQueue.java:1049)
	at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1361)
	at javax.swing.text.StyleContext.reclaim(StyleContext.java:454)
	at javax.swing.text.StyleContext.addAttribute(StyleContext.java:311)
	at javax.swing.text.html.StyleSheet.addAttribute(StyleSheet.java:578)
	at javax.swing.text.StyleContext$NamedStyle.addAttribute(StyleContext.java:1501)
	at javax.swing.text.StyleContext$NamedStyle.setName(StyleContext.java:1312)
	at javax.swing.text.StyleContext$NamedStyle.<init>(StyleContext.java:1259)
	at javax.swing.text.StyleContext.addStyle(StyleContext.java:107)
	at javax.swing.text.StyleContext.<init>(StyleContext.java:87)
	at javax.swing.text.html.StyleSheet.<init>(StyleSheet.java:166)
	at javax.swing.text.html.HTMLEditorKit.getStyleSheet(HTMLEditorKit.java:391)
	at com.intellij.util.ui.UIUtil.<clinit>(UIUtil.java:103)
	at com.intellij.ide.plugins.PluginManager.start(PluginManager.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.ide.Bootstrap.main(Bootstrap.java:39)
	at com.intellij.idea.Main.main(Main.java:78)
```
This is because root is not the owner of the graphics session. What would be your recommendation regarding this issue? If I create the user, then when I start a project, it won't see the python packages that I installed when I built the docker image.

**Comment by rycus86** [comment]
Hi,

I think I have a auto-start script on my laptop that gives the container to X11 with `xhost +`. Note that technically this gives everyone access to the session though.

Also, on the Python packages: if you add

```
  -v ~/.PyCharm.py2:/usr/local/lib/python2.7 \
  -v ~/.PyCharm.py3:/usr/local/lib/python3.5 \
```

Then the packages installed will be available the next time you start the container. Note the __3.5__ on the second line, I need to update the README that still says *3.4*

Let me know if these help!

**Comment by Amschel** [comment]
Thank you, @rycus86 !

Also, for me, the pull version only worked when I called it adding /root/*

```
docker run --rm \
  -e DISPLAY=${DISPLAY} \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v ~/.PyCharm:/root/home/developer/.PyCharm \
  -v ~/.PyCharm.java:/root/home/developer/.java \
  -v ~/.PyCharm.py2:/usr/local/lib/python2.7 \
  -v ~/.PyCharm.py3:/usr/local/lib/python3.4 \
  -v ~/Project:/root/home/developer/Project \
  --name pycharm-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
rycus86/pycharm:latest
```
I don't mind creating the user if from there I can have access to the python packages that I install in docker so I don't need to install them every time I start a new container.

**Comment by rycus86** [comment]
Oh, yeah, that's right. The folder inside the container needs to be inside the home folder of the user inside. So if you changed to root, you need to use root.

**Comment by Amschel** [comment]
I don't quite understand the meaning of these 2 lines and what impact does they have, beside being able to keep the settings between containers:
```
  -v ~/.PyCharm.py2:/usr/local/lib/python2.7 \
  -v ~/.PyCharm.py3:/usr/local/lib/python3.
```
If I don't use them, Pycharm manage to see all the packages that I've installed from the dockerfile, which is exactly what I wanted.

**Comment by rycus86** [comment]
The packages installed from the Dockerfile will always be available when you start a new container from the image. With those two lines, packages installed within the running container (with PyCharm or with pip) will remain installed the next time you start a container from the image - otherwise you'll only have what is installed from the Dockerfile.

Hope this explains it?

**Comment by Amschel** [comment]
I understand that I basically share the folders to mirror the content from the container to the localhost, but I don't understand why when I use this, Pycharm doesn't see the packages installed in the docker image. It's weird, but that is what happens in my machine.

**Comment by rycus86** [comment]
Thinking about it, I suspect the `-v` overrides the folder with the one in your host, so if that folder is empty, that is the one the container will see instead of what was installed there during the `docker build`. I think your choices are:

1. Use the `-v` and install *everything* when the container is running (once)
2. Don't use `-v` amd whenever you need a new package, add it to the Dockerfile, rebuild the image and start the container from this new image

**Comment by Amschel** [comment]
I just checked the folder from localhost and .PyCharm.py3 folder is empty. When I'm not doing the linking with docker, pycharm is indexing the /usr/local/lib/python3.5, which is weird because it's the right path.
This is how I start the container.
```
nvidia-docker run --rm \
  -e DISPLAY=${DISPLAY} \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v $HOME/Docker/shared/.PyCharm:/root/home/developer/.PyCharm \
  -v $HOME/Docker/shared/.PyCharm.java:/root/home/developer/.java \
  -v $HOME/Docker/shared/Project:/root/home/developer/Project \
  -v $HOME/Docker/shared/.PyCharm.py3:/usr/local/lib/python3.5 \
  --name pycharm-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
tf /opt/pycharm/bin/pycharm.sh
```

**Comment by rycus86** [comment]
Try installing something in the container when it is running, like `pip3 install requests` and check if you have it in the host folder.

**Comment by Amschel** [comment]
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/nose-1.3.7.dist-info'
I added a password for the user in dockerfile, rebuild it and did the exact thing, it installed it but .PyCharm.py3 is still empty.

**Comment by Amschel** [comment]
My mistake, I rerun it again and I cannot find pip. So it replaced the folder from the container with an empty one.
```
developer@8c5fc3d82ed2:/usr/local/lib/python3.5$ ls -a
.  ..
```

**Comment by rycus86** [comment]
Did you do the `pip3 install ...` from the Dockerfile or from a running container?

**Comment by Amschel** [comment]
From a running container, but since the folder is empty as I showed in the prev message your suggestion that the folder from the container overrides with the one from host stands up.

**Comment by rycus86** [comment]
Right, OK, that makes sense. :)
Does that help you then with what you're trying to achieve?
I'm happy to help if you have more questions!
