### ISSUE TITLE
Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by weishengchong** [rycus86/docker-pycharm#4]
Hi @rycus86 ,

Thanks for sharing your work!
FYI I have error below that I solved by adding bold text.
Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.

**xhost +local:docker
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -**

docker run --rm \
  -e DISPLAY=${DISPLAY} \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v ~/.PyCharm:/root/.PyCharm \
  -v ~/.PyCharm.java:/root/.java \
  -v ~/.PyCharm.py3:/usr/local/lib/python3.6 \
  -v ~/.PyCharm.share:/root/.local/share/JetBrains \
  -v ~/Project:/home/developer/Project \
  --name pycharm-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
  -v /N:/N \
  **-e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH \**
rycus86/pycharm:latest

reference
https://github.com/NVIDIA/object-detection-tensorrt-example/blob/master/setup_environment.sh

**Comment by weishengchong** [comment]
**-e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH**

**Comment by rycus86** [comment]
Thanks for this! Yep, you either have to go through the steps you mentioned or use the super-insecure `xhost +`.
I have something in the works to make this easier but it's not quite ready for prime-time yet.

**Comment by weishengchong** [comment]
Thanks @rycus86 ! Looking forward to learn from your new works!
